// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function fib(n) {
  if (n < 2) {
    return 1;
  } else {
    return fib(n - 1 | 0) + fib(n - 2 | 0) | 0;
  }
}

console.log("Hello, world!" + String(fib(40)));

exports.fib = fib;
/*  Not a pure module */
