// Generated by js_of_ocaml 3.4.0
(function(a){"use strict";var
ag=" : flags Open_text and Open_binary are not compatible",U="Sys_error",af="Invalid_argument",T=0xf0,ae=0x800,ad="jsError",t=1024,ac="End_of_file",j=0x80,ab="Failure",R="Undefined_recursive_module",S=" : flags Open_rdonly and Open_wronly are not compatible",Q="([^/]*)",P=512,aa="Stack_overflow",b="",B="^",N=" : file already exists",O=0xe0,q=0x3f,M=0xdfff,$="Not_found",L="Assert_failure",o="/",A=128,Y="Sys_blocked_io",Z="fd ",_=0xdc00,K="Out_of_memory",X="Match_failure",f=248,V="Division_by_zero",W="static/";function
aW(d,e,c){var
b=new
Array(c);for(var
a=0;a<c;a++)b[a]=d[e+a];return b}function
G(c,d,a){var
e=String.fromCharCode;if(d==0&&a<=4096&&a==c.length)return e.apply(null,c);var
f=b;for(;0<a;d+=t,a-=t)f+=e.apply(null,aW(c,d,Math.min(a,t)));return f}function
D(c){if(a.Uint8Array)var
d=new(a.Uint8Array)(c.l);else
var
d=new
Array(c.l);var
f=c.c,e=f.length,b=0;for(;b<e;b++)d[b]=f.charCodeAt(b);for(e=c.l;b<e;b++)d[b]=0;c.c=d;c.t=4;return d}function
r(d,e,b,f,c){if(c==0)return 0;if(f==0&&(c>=b.l||b.t==2&&c>=b.c.length)){b.c=d.t==4?G(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else
if(b.t==2&&f==b.c.length){b.c+=d.t==4?G(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else{if(b.t!=4)D(b);var
g=d.c,h=b.c;if(d.t==4)if(f<=e)for(var
a=0;a<c;a++)h[f+a]=g[e+a];else
for(var
a=c-1;a>=0;a--)h[f+a]=g[e+a];else{var
i=Math.min(c,g.length-e);for(var
a=0;a<i;a++)h[f+a]=g.charCodeAt(e+a);for(;a<c;a++)h[f+a]=0}}return 0}function
aj(d,a,e,b,c){return r(d,a,e,b,c)}function
aN(c,a){if(a.repeat)return a.repeat(c);var
d=b,e=0;if(c==0)return d;for(;;){if(c&1)d+=a;c>>=1;if(c==0)return d;a+=a;e++;if(e==9)a.slice(0,1)}}function
ak(a){if(a.t==2)a.c+=aN(a.l-a.c.length,"\0");else
a.c=G(a.c,0,a.c.length);a.t=0}function
am(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
aQ(f){for(var
l=b,d=b,h,g,i,a,c=0,k=f.length;c<k;c++){g=f.charCodeAt(c);if(g<j){for(var
e=c+1;e<k&&(g=f.charCodeAt(e))<j;e++);if(e-c>P){d.substr(0,1);l+=d;d=b;l+=f.slice(c,e)}else
d+=f.slice(c,e);if(e==k)break;c=e}a=1;if(++c<k&&((i=f.charCodeAt(c))&-64)==A){h=i+(g<<6);if(g<O){a=h-0x3080;if(a<j)a=1}else{a=2;if(++c<k&&((i=f.charCodeAt(c))&-64)==A){h=i+(h<<6);if(g<T){a=h-0xe2080;if(a<ae||a>=0xd7ff&&a<0xe000)a=2}else{a=3;if(++c<k&&((i=f.charCodeAt(c))&-64)==A&&g<0xf5){a=i-0x3c82080+(h<<6);if(a<0x10000||a>0x10ffff)a=3}}}}}if(a<4){c-=a;d+="\ufffd"}else
if(a>0xffff)d+=String.fromCharCode(0xd7c0+(a>>10),_+(a&0x3FF));else
d+=String.fromCharCode(a);if(d.length>t){d.substr(0,1);l+=d;d=b}}return l+d}function
aP(a){switch(a.t){case
9:return a.c;default:ak(a);case
0:if(am(a.c)){a.t=9;return a.c}a.t=8;case
8:return aQ(a.c)}}function
k(c,a,b){this.t=c;this.c=a;this.l=b}k.prototype.toString=function(){return aP(this)};k.prototype.slice=function(){var
a=this.t==4?this.c.slice():this.c;return new
k(this.t,a,this.l)};function
aM(b,a){throw[0,b,a]}function
d(a){return new
k(0,a,a.length)}function
ar(b,a){aM(b,d(a))}var
c=[0];function
al(a){ar(c.Invalid_argument,a)}function
p(a){if(a<0)al("Bytes.create");return new
k(a?2:9,b,a)}var
aK=0;function
aB(){return aK++}function
h(a){ar(c.Sys_error,a)}var
n=new
Array();function
E(e){var
a=n[e];if(!a.opened)h("Cannot flush a closed channel");if(!a.buffer||a.buffer==b)return 0;if(a.fd&&c.fds[a.fd]&&c.fds[a.fd].output){var
d=c.fds[a.fd].output;switch(d.length){case
2:d(e,a.buffer);break;default:d(a.buffer)}}a.buffer=b;return 0}if(a.process&&a.process.cwd)var
u=a.process.cwd().replace(/\\/g,o);else
var
u="/static";if(u.slice(-1)!==o)u+=o;function
aE(a){a=a
instanceof
k?a.toString():a;if(a.charCodeAt(0)!=47)a=u+a;var
e=a.split(o),c=[];for(var
d=0;d<e.length;d++)switch(e[d]){case"..":if(c.length>1)c.pop();break;case".":break;case"":if(c.length==0)c.push(b);break;default:c.push(e[d]);break}c.orig=a;return c}function
aL(a){a=a
instanceof
k?a.toString():a;h(a+": No such file or directory")}function
aO(a){return new
k(4,a,a.length)}function
au(){al("index out of bounds")}function
az(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
ax(b,a){if(a>>>0>=b.l)au();return az(b,a)}function
an(a){return a.l}function
ah(){}function
e(a){this.data=a}e.prototype=new
ah();e.prototype.truncate=function(a){var
b=this.data;this.data=p(a|0);r(b,0,this.data,0,a)};e.prototype.length=function(){return an(this.data)};e.prototype.write=function(b,d,g,a){var
c=this.length();if(b+a>=c){var
e=p(b+a),f=this.data;this.data=e;r(f,0,this.data,0,c)}r(d,g,this.data,b,a);return 0};e.prototype.read=function(c,a,d,b){var
e=this.length();r(this.data,c,a,d,b);return 0};e.prototype.read_one=function(a){return ax(this.data,a)};e.prototype.close=function(){};e.prototype.constructor=e;function
g(b,a){this.content={};this.root=b;this.lookupFun=a}g.prototype.nm=function(a){return this.root+a};g.prototype.lookup=function(a){if(!this.content[a]&&this.lookupFun){var
b=this.lookupFun(d(this.root),d(a));if(b!==0)this.content[a]=new
e(b[1])}};g.prototype.exists=function(a){if(a==b)return 1;var
d=a+o,e=new
RegExp(B+d);for(var
c
in
this.content)if(c.match(e))return 1;this.lookup(a);return this.content[a]?1:0};g.prototype.readdir=function(d){var
g=d==b?b:d+o,h=new
RegExp(B+g+Q),e={},c=[];for(var
f
in
this.content){var
a=f.match(h);if(a&&!e[a[1]]){e[a[1]]=true;c.push(a[1])}}return c};g.prototype.is_dir=function(a){var
e=a==b?b:a+o,f=new
RegExp(B+e+Q),g=[];for(var
d
in
this.content){var
c=d.match(f);if(c)return 1}return 0};g.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};g.prototype.open=function(a,b){if(b.rdonly&&b.wronly)h(this.nm(a)+S);if(b.text&&b.binary)h(this.nm(a)+ag);this.lookup(a);if(this.content[a]){if(this.is_dir(a))h(this.nm(a)+" : is a directory");if(b.create&&b.excl)h(this.nm(a)+N);var
c=this.content[a];if(b.truncate)c.truncate();return c}else
if(b.create){this.content[a]=new
e(p(0));return this.content[a]}else
aL(this.nm(a))};g.prototype.register=function(b,a){if(this.content[b])h(this.nm(b)+N);if(a
instanceof
k)this.content[b]=new
e(a);else
if(a
instanceof
Array)this.content[b]=new
e(aO(a));else
if(a.toString){var
c=d(a.toString());this.content[b]=new
e(c)}};g.prototype.constructor=g;function
ai(a){if(a.t!=4)D(a);return a.c}function
aA(a,c,b){b&=0xff;if(a.t!=4){if(c==a.c.length){a.c+=String.fromCharCode(b);if(c+1==a.l)a.t=0;return 0}D(a)}a.c[c]=b;return 0}function
ay(b,a,c){if(a>>>0>=b.l)au();return aA(b,a,c)}var
C=a.Buffer;function
m(a){this.fs=require("fs");this.fd=a}m.prototype=new
ah();m.prototype.truncate=function(a){this.fs.ftruncateSync(this.fd,a|0)};m.prototype.length=function(){return this.fs.fstatSync(this.fd).size};m.prototype.write=function(g,c,d,f){var
b=ai(c);if(!(b
instanceof
a.Uint8Array))b=new(a.Uint8Array)(b);var
e=C.from(b);this.fs.writeSync(this.fd,e,d,f,g);return 0};m.prototype.read=function(h,e,d,g){var
b=ai(e);if(!(b
instanceof
a.Uint8Array))b=new(a.Uint8Array)(b);var
f=C.from(b);this.fs.readSync(this.fd,f,d,g,h);for(var
c=0;c<g;c++)ay(e,d+c,f[d+c]);return 0};m.prototype.read_one=function(d){var
c=new(a.Uint8Array)(1),b=C.from(c);this.fs.readSync(this.fd,b,0,1,d);return b[0]};m.prototype.close=function(){this.fs.closeSync(this.fd)};m.prototype.constructor=m;function
l(a){this.fs=require("fs");this.root=a}l.prototype.nm=function(a){return this.root+a};l.prototype.exists=function(a){return this.fs.existsSync(this.nm(a))?1:0};l.prototype.readdir=function(a){return this.fs.readdirSync(this.nm(a))};l.prototype.is_dir=function(a){return this.fs.statSync(this.nm(a)).isDirectory()?1:0};l.prototype.unlink=function(a){var
b=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a));return b};l.prototype.open=function(f,c){var
a=require("constants"),b=0;for(var
e
in
c)switch(e){case"rdonly":b|=a.O_RDONLY;break;case"wronly":b|=a.O_WRONLY;break;case"append":b|=a.O_WRONLY|a.O_APPEND;break;case"create":b|=a.O_CREAT;break;case"truncate":b|=a.O_TRUNC;break;case"excl":b|=a.O_EXCL;break;case"binary":b|=a.O_BINARY;break;case"text":b|=a.O_TEXT;break;case"nonblock":b|=a.O_NONBLOCK;break}var
d=this.fs.openSync(this.nm(f),b);return new
m(d)};l.prototype.rename=function(b,a){this.fs.renameSync(this.nm(b),this.nm(a))};l.prototype.constructor=l;var
s=u.match(/[^\/]*\//)[0];function
aT(){return typeof
a.process!=="undefined"&&typeof
a.process.versions!=="undefined"&&typeof
a.process.versions.node!=="undefined"}var
v=[];if(aT())v.push({path:s,device:new
l(s)});else
v.push({path:s,device:new
g(s)});v.push({path:s+W,device:new
g(s+W)});function
aX(b){var
f=aE(b),b=f.join(o),e=b+o,c;for(var
d=0;d<v.length;d++){var
a=v[d];if(e.search(a.path)==0&&(!c||c.path.length<a.path.length))c={path:a.path,device:a.device,rest:b.substring(a.path.length,b.length)}}return c}function
F(a){return a.l}function
at(e,f){var
a=n[e],c=d(f),b=F(c);a.file.write(a.offset,c,0,b);a.offset+=b;return 0}function
aU(b){var
c=a;if(c.process&&c.process.stdout&&c.process.stdout.write)c.process.stderr.write(b);else{if(b.charCodeAt(b.length-1)==10)b=b.substr(0,b.length-1);var
d=c.console;d&&d.error&&d.error(b)}}function
aV(b){var
c=a;if(c.process&&c.process.stdout&&c.process.stdout.write)c.process.stdout.write(b);else{if(b.charCodeAt(b.length-1)==10)b=b.substr(0,b.length-1);var
d=c.console;d&&d.log&&d.log(b)}}function
x(d,f,e,a){if(c.fds===undefined)c.fds=new
Array();a=a?a:{};var
b={};b.file=e;b.offset=a.append?e.length():0;b.flags=a;b.output=f;c.fds[d]=b;if(!c.fd_last_idx||d>c.fd_last_idx)c.fd_last_idx=d;return d}function
aY(d,b,i){var
a={};while(b){switch(b[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}b=b[2]}if(a.rdonly&&a.wronly)h(d.toString()+S);if(a.text&&a.binary)h(d.toString()+ag);var
e=aX(d),f=e.device.open(e.rest,a),g=c.fd_last_idx?c.fd_last_idx:0;return x(g+1,at,f,a)}x(0,at,new
e(p(0)));x(1,aV,new
e(p(0)));x(2,aU,new
e(p(0)));function
aF(d){var
b=c.fds[d];if(b.flags.wronly)h(Z+d+" is writeonly");var
a={file:b.file,offset:b.offset,fd:d,opened:true,out:false,refill:null};n[a.fd]=a;return a.fd}function
ao(e){var
d=c.fds[e];if(d.flags.rdonly)h(Z+e+" is readonly");var
a={file:d.file,offset:d.offset,fd:e,opened:true,out:true,buffer:b};n[a.fd]=a;return a.fd}function
aG(){var
b=0;for(var
a=0;a<n.length;a++)if(n[a]&&n[a].opened&&n[a].out)b=[0,n[a].fd,b];return b}function
aD(a){if((a.t&6)!=0)ak(a);return a.c}function
aH(g,d,i,f){var
a=n[g];if(!a.opened)h("Cannot output to a closed channel");var
c;if(i==0&&an(d)==f)c=d;else{c=p(f);r(d,i,c,0,f)}var
b=aD(c),e=b.lastIndexOf("\n");if(e<0)a.buffer+=b;else{a.buffer+=b.substr(0,e+1);E(g);a.buffer+=b.substr(e+1)}return 0}function
ap(b,a,d,c){return aH(b,a,d,c)}function
aI(b,a){var
c=d(String.fromCharCode(a));ap(b,c,0,1);return 0}function
i(d,e,b){if(b&&a.toplevelReloc)d=a.toplevelReloc(b);c[d+1]=e;if(b)c[b]=e}function
as(a){return a}function
aR(f){for(var
g=b,c=g,a,i,d=0,h=f.length;d<h;d++){a=f.charCodeAt(d);if(a<j){for(var
e=d+1;e<h&&(a=f.charCodeAt(e))<j;e++);if(e-d>P){c.substr(0,1);g+=c;c=b;g+=f.slice(d,e)}else
c+=f.slice(d,e);if(e==h)break;d=e}if(a<ae){c+=String.fromCharCode(0xc0|a>>6);c+=String.fromCharCode(j|a&q)}else
if(a<0xd800||a>=M)c+=String.fromCharCode(O|a>>12,j|a>>6&q,j|a&q);else
if(a>=0xdbff||d+1==h||(i=f.charCodeAt(d+1))<_||i>M)c+="\xef\xbf\xbd";else{d++;a=(a<<10)+i-0x35fdc00;c+=String.fromCharCode(T|a>>18,j|a>>12&q,j|a>>6&q,j|a&q)}if(c.length>t){c.substr(0,1);g+=c;c=b}}return g+c}function
aC(a){var
b=9;if(!am(a))b=8,a=aR(a);return new
k(b,a,a.length)}var
aJ={};function
aq(a){return aJ[a]}function
aS(b){if(b
instanceof
Array)return b;if(a.RangeError&&b
instanceof
a.RangeError&&b.message&&b.message.match(/maximum call stack/i))return as(c.Stack_overflow);if(a.InternalError&&b
instanceof
a.InternalError&&b.message&&b.message.match(/too much recursion/i))return as(c.Stack_overflow);if(b
instanceof
a.Error&&aq(ad))return[0,aq(ad),b];return[0,c.Failure,aC(String(b))]}var
I=[f,d(U),-2];i(11,[f,d(R),-12],R);i(10,[f,d(L),-11],L);i(9,[f,d(Y),-10],Y);i(8,[f,d(aa),-9],aa);i(7,[f,d(X),-8],X);i(6,[f,d($),-7],$);i(5,[f,d(V),-6],V);i(4,[f,d(ac),-5],ac);i(3,[f,d(af),-4],af);i(2,[f,d(ab),-3],ab);i(1,I,U);i(0,[f,d(K),-1],K);aB(0);aF(0);var
y=ao(1);ao(2);var
aw=d("Hello, world!");function
z(a){if(3<=a){var
b=z(a-2|0);return z(a-1|0)+b|0}return 1}var
J=d(b+z(40)),H=F(J),w=p(13+H|0);aj(aw,0,w,0,13);aj(J,0,w,13,H);ap(y,w,0,F(w));aI(y,10);E(y);function
av(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{E(d)}catch(a){a=aS(a);if(a[1]!==I)throw a}var
a=c;continue}return 0}}av(aG(0));return}(function(){return this}()));
